### ISSUE TITLE
Motion module doesn't return magnetometer values

### ISSUE THREAD

**Issue by veryalien** [pimoroni/flotilla-python#26]
The python motion module only returns the accelerometer x, y and z values. The magnetometer x, y and z values are not returned (as they aren't defined in the python code!).
It's easy enough to add the 3 missing data values to the motion module code, upgrade the python package manually, and then everything works as expected!

**Comment by RogueM** [comment]
go on, pushed a PR onto us, we can guide you through with that. That said, I'll have a look at this ASAP, but if ou beat us to it, smashing!

**Comment by Gadgetoid** [comment]
This was fixed in eb134f14a27de6190ab322522ec2e772f4ec81cd
