### ISSUE TITLE
Matrix brightness documentation wrong

### ISSUE THREAD

**Issue by veryalien** [pimoroni/flotilla-python#34]
The new matrix documentation seems to be wrong about setting individual matrix pixel brightness.
set_pixel takes x and y coordinates and a state (0 or 1).
set_brightness from 0 to 255 can only be set for the complete matrix, not for each pixel.

**Comment by Gadgetoid** [comment]
D'oh! that'll teach me to write stuff up in a hurry! Thank you for pointing it out.

**Comment by sonntagsgesicht** [comment]
Is there any chance to set pixel brightness individually? Would be great to *draw* 🖼
