### ISSUE TITLE
One line installer fails to install correct dependencies

### ISSUE THREAD

**Issue by helgibbons** [pimoroni/flotilla-python#35]
`curl -sS get.pimoroni.com/flotilla | bash`  tries to install libboost 1.50.0 which is no longer available in Raspbian repositories.  Rest of installer completes but dock isn't detected in Rockpool.

**Comment by Gadgetoid** [comment]
Should be fixed as of https://github.com/pimoroni/flotilla/commit/d830bdc4f63f4a9d1c8299d18f8965137c05dfc3
