### ISSUE TITLE
Online installer does not work with Buster

### ISSUE THREAD

**Issue by ThyWhiteHawk** [pimoroni/flotilla-python#36]
Flotilla "firmware" updater will not run on Buster from the online installer.

It looks like some files have been updated for buster, but the "update_firmware" still needs the lines:
       elif cat /etc/os-release | grep -q "buster"; then
            IS_SUPPORTED=true && IS_EXPERIMENTAL=false

copied into the "raspbian_check()" function.

**Comment by Gadgetoid** [comment]
Good catch- I'm not 100% sure if it will work, but I've added "experimental" support lines for now. Thank you.
